[package]
name = "dotloy"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
directories = "5.0.1"
serde = { version = "1.0.163", features = ["derive"] }
serde_yaml = "0.9.21"
symlink = "0.1.0"
thiserror = "1.0.40"
